package view;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import static jdk.nashorn.internal.objects.NativeString.trim;

import model.Client;
import model.Disc;

import static controller.Controller.*;

import java.io.File;
import javax.swing.JFileChooser;

/**
 * Класс главной формы
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Поле, хранящее номер первого столбца таблицы
     */
    private static final int firstColumn = 0;
    /**
     * Поле, хранящее номер первой строки
     */
    private static final int firstRow = 0;

    /**
     * Конструктор формы
     */
    public MainForm() {
        initComponents();
        clientF.setText("");

        if (getClients().isEmpty()) {
            setClientFieldsEnable(false);
        } else {
            showClientsList();
            jTable2.setRowSelectionInterval(firstRow, firstRow);
            showClientFields();
        }

        if (getDiscs().isEmpty()) {
            setDiscFieldsEnable(false);
        } else {
            showDiscsList();
            jTable1.setRowSelectionInterval(firstRow, firstRow);
            showDiscFields();
        }

        jTable1.requestFocus();
        jDesktopPane1.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField5 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        origTittleF = new javax.swing.JTextField();
        russTittleF = new javax.swing.JTextField();
        directorF = new javax.swing.JTextField();
        genreF = new javax.swing.JTextField();
        durationF = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        releaseyearF = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        ratingF = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        langF = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        countryF = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        descriptionF = new javax.swing.JTextPane();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        actorsF = new javax.swing.JTextPane();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        clientF = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        searchF = new javax.swing.JTextField();
        jButton9 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        clientSurnameF = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        clientPhoneF = new javax.swing.JTextField();
        clientNameF = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        openBase = new javax.swing.JMenuItem();
        mergeBase = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Видеотека");
        setResizable(false);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "#", "Русское название фильма"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setNextFocusableComponent(origTittleF);
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jTable1MouseDragged(evt);
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTable1MouseReleased(evt);
            }
        });
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTable1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTable1KeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setMinWidth(10);
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(30);
            jTable1.getColumnModel().getColumn(0).setMaxWidth(30);
        }

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Название:");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Русское название:");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Режиссёр(ы):");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Жанр:");

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Длительность:");

        origTittleF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                origTittleFKeyReleased(evt);
            }
        });

        russTittleF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                russTittleFFocusLost(evt);
            }
        });
        russTittleF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                russTittleFKeyReleased(evt);
            }
        });

        directorF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                directorFKeyReleased(evt);
            }
        });

        genreF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                genreFKeyReleased(evt);
            }
        });

        durationF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                durationFKeyReleased(evt);
            }
        });

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Год выхода:");

        releaseyearF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                releaseyearFKeyReleased(evt);
            }
        });

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Рейтинг IMDb:");

        ratingF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ratingFKeyReleased(evt);
            }
        });

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Языки:");

        langF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                langFKeyReleased(evt);
            }
        });

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Страна:");

        countryF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                countryFKeyReleased(evt);
            }
        });

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("В гланых ролях:");

        descriptionF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                descriptionFMousePressed(evt);
            }
        });
        descriptionF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                descriptionFKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                descriptionFKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(descriptionF);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 82, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("мин");

        actorsF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                actorsFKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                actorsFKeyReleased(evt);
            }
        });
        jScrollPane3.setViewportView(actorsF);

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Описание фильма:");

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("Диск на руках у:");

        jButton8.setText("Диск сдан");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        clientF.setText("client");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(jLabel13))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel11)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(clientF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(durationF, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel12)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(releaseyearF, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ratingF, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(origTittleF, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(russTittleF, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(directorF, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(genreF, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(264, 264, 264)
                                .addComponent(countryF, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 454, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(langF, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel9)
                                        .addGap(202, 202, 202))
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 454, Short.MAX_VALUE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(origTittleF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(russTittleF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(directorF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(genreF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ratingF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(releaseyearF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(durationF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel12)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(countryF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(langF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(69, 69, 69)
                        .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jButton8)
                    .addComponent(clientF))
                .addContainerGap())
        );

        jButton1.setText("Добавить диск");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText("Удалить диск");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton4.setText("Сохранить в файл");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        searchF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                searchFKeyPressed(evt);
            }
        });

        jButton9.setText("Поиск");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "#", "Имя", "Фамилия", "Телефон"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jTable2MouseDragged(evt);
            }
        });
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable2MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTable2MouseReleased(evt);
            }
        });
        jTable2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTable2KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTable2KeyReleased(evt);
            }
        });
        jScrollPane4.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(0).setMinWidth(10);
            jTable2.getColumnModel().getColumn(0).setPreferredWidth(30);
            jTable2.getColumnModel().getColumn(0).setMaxWidth(30);
            jTable2.getColumnModel().getColumn(1).setMinWidth(40);
            jTable2.getColumnModel().getColumn(2).setMinWidth(80);
        }

        jButton2.setText("Добавить клиента");

        jButton5.setText("Добавить клиента");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Удалить клиента");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton10.setText("Выдать диск");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jLabel14.setText("Имя:");

        jLabel15.setText("Фамилия:");

        clientSurnameF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                clientSurnameFFocusLost(evt);
            }
        });
        clientSurnameF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                clientSurnameFKeyReleased(evt);
            }
        });

        jLabel16.setText("Телефон:");

        clientPhoneF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                clientPhoneFFocusLost(evt);
            }
        });
        clientPhoneF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                clientPhoneFKeyReleased(evt);
            }
        });

        clientNameF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                clientNameFFocusLost(evt);
            }
        });
        clientNameF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                clientNameFKeyReleased(evt);
            }
        });

        jMenu1.setText("Файл");

        openBase.setText("Открыть базу");
        openBase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openBaseActionPerformed(evt);
            }
        });
        jMenu1.add(openBase);

        mergeBase.setText("Слияние баз");
        mergeBase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mergeBaseActionPerformed(evt);
            }
        });
        jMenu1.add(mergeBase);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(searchF, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(clientSurnameF, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(clientPhoneF, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(clientNameF, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 601, Short.MAX_VALUE)
                    .addComponent(jButton2)
                    .addGap(0, 601, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(clientNameF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(clientSurnameF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(clientPhoneF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton5)
                            .addComponent(jButton6)
                            .addComponent(jButton10)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(searchF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton3))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 270, Short.MAX_VALUE)
                    .addComponent(jButton2)
                    .addGap(0, 271, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    /**
     * Метод нажатия кнопки "Сохранить".
     * Вызывается метод сохранения базы в файл.
     * @param evt 
     */
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {
        // /GEN-FIRST:event_jButton4ActionPerformed
        saveChanges();
    }
                                            

    /**
     * Метод нажатия кнопки "Удалить диск".
     * Удаляется диск, выбранный в таблице jTable1.
     * Если таблица становится полностью пустой, текстовые поля диска
     * становятся недоступными.
     * @param evt 
     */
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {
//GEN-FIRST:event_jButton3ActionPerformed
        int x = jTable1.getSelectedRow();
        if (x != -1) {
            deleteDisc((int) jTable1.getValueAt(x, firstColumn));
            clearDiscFields();
            clearDiscsList();
            showDiscsList();
        }
        if (getDiscs().isEmpty()) {
            setDiscFieldsEnable(false);
        } else if (x != 0) {
            jTable1.setRowSelectionInterval(x - 1, x - 1);
            showDiscFields();
            //jTable1.setRowSelectionInterval(x - 1, x - 1);
        } else {
            jTable1.setRowSelectionInterval(firstRow, firstColumn);
            showDiscFields();
            //jTable1.setRowSelectionInterval(0, 0);
        }
    }
//GEN-LAST:event_jButton3ActionPerformed

    /**
     * Метод нажатия кнопки "Добавить диск".
     * В конец таблицы jTable1 добавляется пустая строка диска. 
     * Текстовые поля диска очищаются.
     * @param evt 
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
//GEN-FIRST:event_jButton1ActionPerformed
        clearDiscFields();
        Disc disc = new Disc();
        setDisc(disc);
        showDiscsList();
        jTable1.setRowSelectionInterval(jTable1.getRowCount() - 1, jTable1.getRowCount() - 1);
        showDiscFields();
        setDiscFieldsEnable(true);
    }
//GEN-LAST:event_jButton1ActionPerformed

    /**
     * Метод нажатия кнопки "Диск сдан".
     * Вызывается метод установки clientID (ID клиента) = 0
     * у диска, выбранного в таблице jTable1.
     * @param evt 
     */
    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {
//GEN-FIRST:event_jButton8ActionPerformed
        int x = jTable1.getSelectedRow();
        if (x != -1) {
            setClient(getDisc((int) jTable1.getValueAt(x, firstColumn)).getDiskID(), firstColumn);
            clientF.setText("Диск не на руках");
        }
    }
//GEN-LAST:event_jButton8ActionPerformed

    /**
     * Метод нажатия кнопки "Поиск".
     * Вызыается метод поиска по введенным в текстовое поле searchF словам.
     * Результат выводит в таблицу jTable1.
     * @param evt 
     */
    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {
//GEN-FIRST:event_jButton9ActionPerformed
//        clearDiscFields();
//        clearDiscsList();
//        search(searchF.getText());
//        showDiscsList();
//        jTable1.setRowSelectionInterval(firstRow, firstRow);
//       // if ("".equals(searchF.getText())) {
//        //    searchF.setText("Введите ключевые слова");
//       // }
//        showDiscFields();
        showDiscsList();
        showDiscFields();
    }
//GEN-LAST:event_jButton9ActionPerformed

    /**
     * Метод отпускания клавиши на таблице jTable1.
     * @param evt 
     */
    private void jTable1KeyReleased(java.awt.event.KeyEvent evt) {
//GEN-FIRST:event_jTable1KeyReleased
        if (evt.getKeyChar() == KeyEvent.VK_ENTER || evt.getKeyChar() == KeyEvent.VK_UP
                || evt.getKeyChar() == KeyEvent.VK_DOWN || evt.getKeyChar() == KeyEvent.VK_TAB) {
            showDiscFields();
        }
    }
//GEN-LAST:event_jTable1KeyReleased

    /**
     * Метод, отлавливающие отпускание клавиши в текстовом поле
     * origTittleF. Обновляет информацию в поле диска originalTitle на то, что введено
     * в данном поле.
     * @param evt 
     */
    private void origTittleFKeyReleased(java.awt.event.KeyEvent evt) {
//GEN-FIRST:event_origTittleFKeyReleased
        if (evt.getKeyChar() == KeyEvent.VK_TAB) {
            descriptionF.setText(trim(descriptionF.getText()));
        } else {
            try {
                getDisc((int) jTable1.getValueAt(jTable1.getSelectedRow(), firstColumn))
                        .setOriginalTitle(trim(origTittleF.getText()));
            } catch (Exception e) {
            }
        }
    }
//GEN-LAST:event_origTittleFKeyReleased

    /**
     * Метод, отлавливающие отпускание клавиши в текстовом поле
     * russTittleF. Обновляет информацию в поле диска russianTitle на то, что введено
     * в данном поле.
     * @param evt 
     */
    private void russTittleFKeyReleased(java.awt.event.KeyEvent evt) {
//GEN-FIRST:event_russTittleFKeyReleased
        try {
            getDisc((int) jTable1.getValueAt(jTable1.getSelectedRow(), firstColumn))
                    .setRussianTitle(trim(russTittleF.getText()));
        } catch (Exception e) {
        }
    }
//GEN-LAST:event_russTittleFKeyReleased

    /**
     * Метод, отлавливающие отпускание клавиши в текстовом поле
     * directorF. Обновляет информацию в поле диска director на то, что введено
     * в данном поле.
     * @param evt 
     */
    private void directorFKeyReleased(java.awt.event.KeyEvent evt) {
//GEN-FIRST:event_directorFKeyReleased
        try {
            getDisc((int) jTable1.getValueAt(jTable1.getSelectedRow(), firstColumn))
                    .setDirector(trim(directorF.getText()));
        } catch (Exception e) {
        }
    }
//GEN-LAST:event_directorFKeyReleased

    /**
     * Метод, отлавливающие отпускание клавиши в текстовом поле
     * genreF. Обновляет информацию в поле диска genre на то, что введено
     * в данном поле.
     * @param evt 
     */
    private void genreFKeyReleased(java.awt.event.KeyEvent evt) {
//GEN-FIRST:event_genreFKeyReleased
        try {
            getDisc((int) jTable1.getValueAt(jTable1.getSelectedRow(), firstColumn))
                    .setGenre(trim(genreF.getText()));
        } catch (Exception e) {
        }
    }
//GEN-LAST:event_genreFKeyReleased

    /**
     * Метод, отлавливающие отпускание клавиши в текстовом поле
     * durationF. Обновляет информацию в поле диска duration на то, что введено
     * в данном поле.
     * @param evt 
     */
    private void durationFKeyReleased(java.awt.event.KeyEvent evt) {
        // /GEN-FIRST:event_durationFKeyReleased
        try {
            getDisc((int) jTable1.getValueAt(jTable1.getSelectedRow(), firstColumn))
                    .setDuration(Integer.parseInt(trim(durationF.getText())));
        } catch (NumberFormatException e) {
            getDisc((int) jTable1.getValueAt(jTable1.getSelectedRow(), firstColumn)).setDuration(0);
        }
    }
                                         

    /**
     * Метод, отлавливающие отпускание клавиши в текстовом поле
     * releaseyearF. Обновляет информацию в поле диска releaseyear на то, что введено
     * в данном поле.
     * @param evt
     */
    private void releaseyearFKeyReleased(java.awt.event.KeyEvent evt) {
        /// /GEN-FIRST:event_releaseyearFKeyReleased
        try {
            getDisc((int) jTable1.getValueAt(jTable1.getSelectedRow(), firstColumn))
                    .setReleaseYear(Short.parseShort(trim(releaseyearF.getText())));
        } catch (NumberFormatException e) {
            getDisc((int) jTable1.getValueAt(jTable1.getSelectedRow(), firstColumn)).setReleaseYear((short) 0);
        }
    }
                                            

    /**
     * Метод, отлавливающие отпускание клавиши в текстовом поле
     * ratingF. Обновляет информацию в поле диска rating на то, что введено
     * в данном поле.
     * @param evt 
     */
    private void ratingFKeyReleased(java.awt.event.KeyEvent evt) {
//GEN-FIRST:event_ratingFKeyReleased
        try {
            getDisc((int) jTable1.getValueAt(jTable1.getSelectedRow(), firstColumn))
                    .setRating(Double.parseDouble(trim(ratingF.getText())));
        } catch (NumberFormatException e) {
            getDisc((int) jTable1.getValueAt(jTable1.getSelectedRow(), firstColumn)).setRating(0);
        }
    }
//GEN-LAST:event_ratingFKeyReleased

    /**
     * Метод, отлавливающие отпускание клавиши в текстовом поле
     * langF. Обновляет информацию в поле диска languages на то, что введено
     * в данном поле.
     * @param evt 
     */
    private void langFKeyReleased(java.awt.event.KeyEvent evt) {
//GEN-FIRST:event_langFKeyReleased
        try {
            getDisc((int) jTable1.getValueAt(jTable1.getSelectedRow(), firstColumn)
            ).setLanguages(trim(langF.getText()));
        } catch (Exception e) {
        }
    }
//GEN-LAST:event_langFKeyReleased

    /**
     * Метод, отлавливающие отпускание клавиши в текстовом поле
     * countryF. Обновляет информацию в поле диска country на то, что введено
     * в данном поле.
     * @param evt 
     */
    private void countryFKeyReleased(java.awt.event.KeyEvent evt) {
//GEN-FIRST:event_countryFKeyReleased
        try {
            getDisc((int) jTable1.getValueAt(jTable1.getSelectedRow(), firstColumn))
                    .setCountry(trim(countryF.getText()));
        } catch (Exception e) {
        }
    }
//GEN-LAST:event_countryFKeyReleased

    /**
     * Метод, отлавливающие отпускание клавиши в текстовом поле
     * actorsF. Обновляет информацию в поле диска actors на то, что введено
     * в данном поле.
     * @param evt 
     */
    private void actorsFKeyReleased(java.awt.event.KeyEvent evt) {
//GEN-FIRST:event_actorsFKeyReleased
        try {
            getDisc((int) jTable1.getValueAt(jTable1.getSelectedRow(), firstColumn))
                    .setActors(trim(actorsF.getText()));
        } catch (Exception e) {
        }
    }
//GEN-LAST:event_actorsFKeyReleased

    /**
     * Метод, отлавливающие отпускание клавиши в текстовом поле
     * descriptionF.
     * @param evt 
     */
    private void descriptionFKeyReleased(java.awt.event.KeyEvent evt) {
//GEN-FIRST:event_descriptionFKeyReleased
        if (evt.getKeyChar() == KeyEvent.VK_TAB) {
            actorsF.setText(trim(actorsF.getText()));
            descriptionF.setText(trim(descriptionF.getText()));
        } else {
            try {
                getDisc((int) jTable1.getValueAt(jTable1.getSelectedRow(), firstColumn))
                        .setDescription(trim(descriptionF.getText()));
            } catch (Exception e) {
            }
        }
    }
//GEN-LAST:event_descriptionFKeyReleased

    /**
     * Метод, отлавливающий нажатие клавиши мышки.
     * Отображает информацию о диске, выбранном в таблице jTable.
     * @param evt 
     */
    private void jTable1MousePressed(java.awt.event.MouseEvent evt) {
//GEN-FIRST:event_jTable1MousePressed
        jTable1.setRowSelectionInterval(jTable1.getSelectedRow(), jTable1.getSelectedRow());
        showDiscFields();
    }
//GEN-LAST:event_jTable1MousePressed

    /**
     * Метод нажатия кнопки "Удалить клиента".
     * Выбранный клиент в таблицы jTable2 удаляется.
     * Если таблица становится полностью пустой, текстовые поля клиента
     * становятся недоступными.
     * @param evt 
     */
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {
//GEN-FIRST:event_jButton6ActionPerformed
        int x = jTable2.getSelectedRow();
        if (x != -1) {
            deleteClient((int) jTable2.getValueAt(x, firstColumn));
            clientNameF.setText("");
            clientSurnameF.setText("");
            clientPhoneF.setText("");
            clearClientsList();
            showClientsList();
            showDiscFields();
        }
        if (getClients().isEmpty()) {
            setClientFieldsEnable(false);
        } else if (x != 0) {
            jTable2.setRowSelectionInterval(x - 1, x - 1);
            showClientFields();
            //jTable2.setRowSelectionInterval(x - 1, x - 1);
        } else {
            jTable2.setRowSelectionInterval(firstRow, firstRow);
            showClientFields();
            //jTable2.setRowSelectionInterval(0, 0);
        }

    }
//GEN-LAST:event_jButton6ActionPerformed

    /**
     * Метод нажатия кнопки "Добавить клиента".
     * В конец таблицы jTable2 добавляется пустая строка.
     * Текстовые поля клиента очищаются.
     * @param evt 
     */
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {
//GEN-FIRST:event_jButton5ActionPerformed
        clearClientFields();
        Client client = new Client();
        client.setName("");
        client.setSurname("");
        client.setPhone("");
        setClient(client);
        showClientsList();
        setClientFieldsEnable(true);
        jTable2.setRowSelectionInterval(jTable2.getRowCount() - 1, jTable2.getRowCount() - 1);
    }
//GEN-LAST:event_jButton5ActionPerformed

    /**
     * Метод нажатия кнопки "Выдать диск".
     * Выбранному клиенту в таблицы jTable2 выдается диск, выбранный
     * в таблице jTable1.
     * @param evt 
     */
    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {
//GEN-FIRST:event_jButton10ActionPerformed
        int x = jTable1.getSelectedRow();
        int y = jTable2.getSelectedRow();
        if (x != -1 && y != -1) {
            setClient((int) jTable1.getValueAt(x, firstColumn), (int) jTable2.getValueAt(y, firstColumn));
            showDiscFields();
        } else {
            JOptionPane.showMessageDialog(this, "Вы не выбрали клиента");
        }
    }
//GEN-LAST:event_jButton10ActionPerformed

    /**
     * Метод клика по таблице jTable2.
     * Вызывается метод, отображающий поля выбранного клиента.
     * @param evt 
     */
    private void jTable2MousePressed(java.awt.event.MouseEvent evt) {
//GEN-FIRST:event_jTable2MousePressed
        showClientFields();
    }
//GEN-LAST:event_jTable2MousePressed

    /**
     * Метод отпускания клавиши в текстовом поле clientNameF.
     * Вызывается метод, обновляющий информацию клиента в его поле name
     * на то, что введено в данном текстовом поле.
     * @param evt 
     */
    private void clientNameFKeyReleased(java.awt.event.KeyEvent evt) {
//GEN-FIRST:event_clientNameFKeyReleased
        try {
            getClient((int) jTable2.getValueAt(jTable2.getSelectedRow(), firstColumn))
                    .setName(trim(clientNameF.getText()));
        } catch (Exception e) {
        }
    }
//GEN-LAST:event_clientNameFKeyReleased

    /**
     * Метод отпускания клавиши в текстовом поле clientSurnameF.
     * Вызывается метод, обновляющий информацию клиента в его поле surname
     * на то, что введено в данном текстовом поле.
     * @param evt 
     */
    private void clientSurnameFKeyReleased(java.awt.event.KeyEvent evt) {
//GEN-FIRST:event_clientSurnameFKeyReleased
        try {
            getClient((int) jTable2.getValueAt(jTable2.getSelectedRow(), firstColumn))
                    .setSurname(trim(clientSurnameF.getText()));
        } catch (Exception e) {
        }
    }
//GEN-LAST:event_clientSurnameFKeyReleased

    /**
     * Метод отпускания клавиши в текстовом поле clientPhoneF.
     * Вызывается метод, обновляющий информацию клиента в его поле phone
     * на то, что введено в данном текстовом поле.
     * @param evt 
     */
    private void clientPhoneFKeyReleased(java.awt.event.KeyEvent evt) {
//GEN-FIRST:event_clientPhoneFKeyReleased
        try {
            getClient((int) jTable2.getValueAt(jTable2.getSelectedRow(), firstColumn))
                    .setPhone(trim(clientPhoneF.getText()));
        } catch (Exception e) {
        }
    }
//GEN-LAST:event_clientPhoneFKeyReleased

    /**
     * Метод отпускания клавиши на таблице jTable2.
     * Отлавливает нажатие стрелок и клавиш Tab, Enter.
     * Вызывает метод отображения полей клиента.
     * @param evt 
     */
    private void jTable2KeyReleased(java.awt.event.KeyEvent evt) {
//GEN-FIRST:event_jTable2KeyReleased
        if (evt.getKeyChar() == KeyEvent.VK_ENTER || evt.getKeyChar() == KeyEvent.VK_UP
                || evt.getKeyChar() == KeyEvent.VK_DOWN || evt.getKeyChar() == KeyEvent.VK_TAB) {
            showClientFields();
        }
    }
//GEN-LAST:event_jTable2KeyReleased

    /**
     * Метод отлавливающий нажатие кнопки "Открыть базу".
     * Вызывает метод, открывающий базу из выбранного файла.
     * @param evt 
     */
    private void openBaseActionPerformed(java.awt.event.ActionEvent evt) {
//GEN-FIRST:event_openBaseActionPerformed
        JFileChooser dialog = new JFileChooser();
        if (dialog.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            File file = dialog.getSelectedFile();
            openBase(file.getPath());
        }

        reloadTables();
    }
//GEN-LAST:event_openBaseActionPerformed

    /**
     * Метод отлавливающий нажатие кнопки "Слияние баз".
     * Вызывает метод, сливающий открытую базу и базу из выбранного файла.
     * @param evt 
     */
    private void mergeBaseActionPerformed(java.awt.event.ActionEvent evt) {
//GEN-FIRST:event_mergeBaseActionPerformed
        JFileChooser dialog = new JFileChooser();
        if (dialog.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            File file = dialog.getSelectedFile();
            mergeBase(file.getPath());
        }

        reloadTables();
    }
//GEN-LAST:event_mergeBaseActionPerformed

    /**
     * Метод, отлавливающий нажатие клавиши в текстовом поле actorsF.
     * @param evt 
     */
    private void actorsFKeyPressed(java.awt.event.KeyEvent evt) {
//GEN-FIRST:event_actorsFKeyPressed
        if (evt.getKeyChar() == KeyEvent.VK_TAB) {
            actorsF.setText(trim(actorsF.getText()));
            descriptionF.setText(trim(descriptionF.getText()));
            descriptionF.requestFocus();
        }
    }
//GEN-LAST:event_actorsFKeyPressed

    /**
     * Метод, отлавливающий нажатие клавиши в текстовом поле decriptionF.
     * @param evt 
     */
    private void descriptionFKeyPressed(java.awt.event.KeyEvent evt) {
//GEN-FIRST:event_descriptionFKeyPressed
        if (evt.getKeyChar() == KeyEvent.VK_TAB) {
            actorsF.setText(trim(actorsF.getText()));
            descriptionF.setText(trim(descriptionF.getText()));
            origTittleF.requestFocus();
        }
    }
//GEN-LAST:event_descriptionFKeyPressed

    /**
     * Метод, отлавливающий нажатие мышкой в текстовом поле descriptionF.
     * @param evt 
     */
    private void descriptionFMousePressed(java.awt.event.MouseEvent evt) {
                                                  
        int x = descriptionF.getCaretPosition();
        descriptionF.setText(trim(descriptionF.getText()));
        try {
            descriptionF.setCaretPosition(x);
        } catch (IllegalArgumentException e) {

        }
    }
    // /GEN-LAST:event_descriptionFMousePressed

    /**
     * Метод нажатия (зажатия) клавиши на таблице jTable1.
     * @param evt 
     */
    private void jTable1KeyPressed(java.awt.event.KeyEvent evt) {
//GEN-FIRST:event_jTable1KeyPressed
        if (evt.getKeyChar() == KeyEvent.VK_ENTER || evt.getKeyChar() == KeyEvent.VK_UP
                || evt.getKeyChar() == KeyEvent.VK_DOWN || evt.getKeyChar() == KeyEvent.VK_TAB) {
            showDiscFields();
        }
    }
//GEN-LAST:event_jTable1KeyPressed

    /**
     * Метод нажатия (зажатия) клавиши на таблице jTable2.
     * @param evt 
     */
    private void jTable2KeyPressed(java.awt.event.KeyEvent evt) {
//GEN-FIRST:event_jTable2KeyPressed
        if (evt.getKeyChar() == KeyEvent.VK_ENTER || evt.getKeyChar() == KeyEvent.VK_UP
                || evt.getKeyChar() == KeyEvent.VK_DOWN || evt.getKeyChar() == KeyEvent.VK_TAB) {
            showClientFields();
        }
    }
//GEN-LAST:event_jTable2KeyPressed

    /**
     * Метод, отлавливающий потерю фокуса в текстовом поле russTittleF. 
     * Вызывает методы отображения полей диска и обновленного списка
     * дисков.
     * @param evt 
     */
    private void russTittleFFocusLost(java.awt.event.FocusEvent evt) {
//GEN-FIRST:event_russTittleFFocusLost
        showDiscsList();
    }
//GEN-LAST:event_russTittleFFocusLost

    /**
     * Метод, отлавливающий потерю фокуса в текстовом поле
     * clientNameF. 
     * Вызывает методы отображения полей клиента и обновленного списка
     * клиентов.
     * @param evt 
     */
    private void clientNameFFocusLost(java.awt.event.FocusEvent evt) {
//GEN-FIRST:event_clientNameFFocusLost
        showDiscFields();
        showClientsList();
    }
//GEN-LAST:event_clientNameFFocusLost

    /**
     * Метод, отлавливающий потерю фокуса в текстовом поле
     * clientSurnameF. 
     * Вызывает методы отображения полей клиента и обновленного списка
     * клиентов.
     * @param evt 
     */
    private void clientSurnameFFocusLost(java.awt.event.FocusEvent evt) {
//GEN-FIRST:event_clientSurnameFFocusLost
        showDiscFields();
        showClientsList();
    }
//GEN-LAST:event_clientSurnameFFocusLost

    /**
     * Метод, отлавливающий потерю фокуса в текстовом поле
     * clientPhoneF. 
     * Вызывает методы отображения полей клиента и обновленного списка
     * клиентов.
     * @param evt 
     */
    private void clientPhoneFFocusLost(java.awt.event.FocusEvent evt) {
        // /GEN-FIRST:event_clientPhoneFFocusLost
        showDiscFields();
        showClientsList();
    }
                                          

    /**
     * Метод, отлавливающий отпускание клавиши мышки.
     * Отображает информацию о выбранном в таблице jTable1 диске.
     * @param evt 
     */
    private void jTable1MouseReleased(java.awt.event.MouseEvent evt) {
//GEN-FIRST:event_jTable1MouseReleased
        showDiscFields();
    }
//GEN-LAST:event_jTable1MouseReleased

    /**
     * Метод, отслеживающий отпускание клавиши мышки в таблице jTable2.
     * @param evt 
     */
    private void jTable2MouseReleased(java.awt.event.MouseEvent evt) {
//GEN-FIRST:event_jTable2MouseReleased
        showClientFields();
    }
//GEN-LAST:event_jTable2MouseReleased

    /**
     * Метод отлавливающий перемещение мыши с зажатой клавишей по таблице jTable1. 
     * Отображаются поля диска.
     * @param evt 
     */
    private void jTable1MouseDragged(java.awt.event.MouseEvent evt) {
//GEN-FIRST:event_jTable1MouseDragged
        showDiscFields();
    }
//GEN-LAST:event_jTable1MouseDragged


    /**
     * Метод отлавливающий перемещение мыши с зажатой клавишей по таблице jTable2. 
     * Отображаются поля клиента.
     * @param evt 
     */
    private void jTable2MouseDragged(java.awt.event.MouseEvent evt) {
//GEN-FIRST:event_jTable2MouseDragged
        showClientFields();
    }
//GEN-LAST:event_jTable2MouseDragged

    private void searchFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchFKeyPressed
        if (evt.getKeyChar()==KeyEvent.VK_ENTER)
            jButton9.doClick();
    }//GEN-LAST:event_searchFKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            /**
             * No description.
             */
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane actorsF;
    private javax.swing.JLabel clientF;
    private javax.swing.JTextField clientNameF;
    private javax.swing.JTextField clientPhoneF;
    private javax.swing.JTextField clientSurnameF;
    private javax.swing.JTextField countryF;
    private javax.swing.JTextPane descriptionF;
    private javax.swing.JTextField directorF;
    private javax.swing.JTextField durationF;
    private javax.swing.JTextField genreF;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField langF;
    private javax.swing.JMenuItem mergeBase;
    private javax.swing.JMenuItem openBase;
    private javax.swing.JTextField origTittleF;
    private javax.swing.JTextField ratingF;
    private javax.swing.JTextField releaseyearF;
    private javax.swing.JTextField russTittleF;
    private javax.swing.JTextField searchF;
    // End of variables declaration//GEN-END:variables

    /**
     * Метод очистки текстовых полей диска.
     */
    private void clearDiscFields() {
        origTittleF.setText("");
        russTittleF.setText("");
        directorF.setText("");
        genreF.setText("");
        durationF.setText("");
        releaseyearF.setText("");
        ratingF.setText("");
        langF.setText("");
        countryF.setText("");
        actorsF.setText("");
        descriptionF.setText("");
        clientF.setText("");
    }

    /**
     * Метод очистки текстовых полей клиента.
     */
    public void clearClientFields() {
        clientNameF.setText("");
        clientSurnameF.setText("");
        clientPhoneF.setText("");
    }

    /**
     * Метод очистки таблицы дисков.
     */
    private void clearDiscsList() {
        DefaultTableModel dm = (DefaultTableModel) jTable1.getModel();
        while (dm.getRowCount() > 0) {
            dm.removeRow(0);
        }
    }

    /**
     * Метод отображения списка дисков в таблице jTable1.
     */
    private void showDiscsList() {
        int x = jTable1.getSelectedRow();
        clearDiscsList();
        jTable1 = showDiscs(jTable1, searchF.getText());
        if (x >= 0) {
            jTable1.setRowSelectionInterval(x, x);
        }
    }

    /**
     * Метод, отображающий информацию о диске, выбранном в таблице jTable1
     * в текстовые поля диска.
     */
    private void showDiscFields() {
        int first = (int) jTable1.getValueAt(jTable1.getSelectedRow(), firstColumn);
        if (first != 0) {
            Disc disc = getDiscByNumber(first);

            origTittleF.setText(disc.getOriginalTitle());
            russTittleF.setText(disc.getRussianTitle());
            directorF.setText(disc.getDirector());
            genreF.setText(disc.getGenre());
            durationF.setText(Integer.toString(disc.getDuration()));
            releaseyearF.setText(Short.toString(disc.getReleaseYear()));
            ratingF.setText(Double.toString(disc.getRating()));
            langF.setText(disc.getLanguages());
            countryF.setText(disc.getCountry());
            actorsF.setText(disc.getActors());
            descriptionF.setText(disc.getDescription());
            try {
                clientF.setText(getClient(disc.getClientID()).getName() + " "
                        + getClient(disc.getClientID()).getSurname());
                for (int i = 0; i < jTable2.getRowCount(); i++) {
                    if (disc.getClientID() == (int) jTable2.getValueAt(i, firstColumn)) {
                        jTable2.setRowSelectionInterval(i, i);
                        showClientFields();
                        break;
                    }
                }
            } catch (Exception e) {
                disc.setClientID(0);
                clientF.setText("Диск не на руках");
            }

            if (getDiscs().isEmpty()) {
                setDiscFieldsEnable(false);
            }
        }
    }

    /**
     * Метод устанавливающий доступность полей диска
     * в соответствии спереданным булевским параметром flag.
     * @param flag Параметр определяющий доступность полей.
     */
    private void setDiscFieldsEnable(boolean flag) {
        origTittleF.setEnabled(flag);
        russTittleF.setEnabled(flag);
        directorF.setEnabled(flag);
        genreF.setEnabled(flag);
        durationF.setEnabled(flag);
        releaseyearF.setEnabled(flag);
        ratingF.setEnabled(flag);
        langF.setEnabled(flag);
        countryF.setEnabled(flag);
        actorsF.setEnabled(flag);
        descriptionF.setEnabled(flag);
    }

    /**
     * Метод очистки таблицы клиентов.
     */
    private void clearClientsList() {
        DefaultTableModel dm = (DefaultTableModel) jTable2.getModel();
        while (dm.getRowCount() > 0) {
            dm.removeRow(0);
        }
    }

    /**
     * Метод отображения списка клиентов в таблице jTable2.
     */
    private void showClientsList() {
        int x = jTable2.getSelectedRow();
        clearClientsList();
        jTable2 = showClients(jTable2);
        if (x >= 0) {
            jTable2.setRowSelectionInterval(x, x);
        }
    }


    /**
     * Метод, отображающий информацию о клиенте, выбранном в таблице jTable2
     * в текстовые поля клиента.
     */
    private void showClientFields() {
        int first = (int) jTable2.getValueAt(jTable2.getSelectedRow(), firstColumn);
        if (first != 0) {
            Client client = getClient(first);
            clientNameF.setText(client.getName());
            clientSurnameF.setText(client.getSurname());
            clientPhoneF.setText(client.getPhone());
        }

        if (getClients().isEmpty()) {
            setClientFieldsEnable(false);
        }
    }


    /**
     * Метод устанавливающий доступность полей клиента
     * в соответствии спереданным булевским параметром flag.
     * @param flag Параметр определяющий доступность полей.
     */
    private void setClientFieldsEnable(boolean flag) {
        clientNameF.setEnabled(flag);
        clientSurnameF.setEnabled(flag);
        clientPhoneF.setEnabled(flag);
    }


    /**
     * Метод обновления списка в обоих таблицах.
     */
    private void reloadTables() {
        if (getClients().isEmpty()) {
            setClientFieldsEnable(false);
        } else {
            setClientFieldsEnable(true);
            showClientsList();
            jTable2.setRowSelectionInterval(firstRow, firstRow);
            showClientFields();
        }

        if (getDiscs().isEmpty()) {
            setDiscFieldsEnable(false);
        } else {
            setDiscFieldsEnable(true);
            clearDiscsList();
            showDiscsList();
            jTable1.setRowSelectionInterval(firstRow, firstRow);
            showDiscFields();
        }
    }
}
